# Basic Information 
title: Chaoyun Wang
chinese_name: 王超运
position: Ph.D.
affiliation: Xi'an Jiaotong University
affiliation_link: http://en.xjtu.edu.cn
email: chaoyunwang@stu.xjtu.edu.cn

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: personal homepage
description: Personal academic homepage of Chaoyun Wang.
canonical: https://chaoyunwang.github.io/
asset_version: 20261008-01

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=eWQCr5QAAAAJ
cv_link: https://drive.google.com/file/d/14PEiBZ9heJWBbJ9HAddOK9DOnHmmncAu/view?usp=sharing
cv_zh_link: https://drive.google.com/file/d/1dOCU_GCXYF3PaTveOKa1fUUxlLS9Ox-b/view?usp=sharing
github_link: https://github.com/chaoyunwang
#linkedin: https://www.linkedin.com/
#twitter: https://twitter.com/

# Images
avatar: ./assets/img/avatar.png
wechat_qr: ./assets/img/wechat_qr.png

# Footnote
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

## Google Analytics ID
## Please remove this if you don't use Google Analytics
#google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
